### PR TITLE
Add completion_time_in_minutes to our seed files

### PR DESCRIPTION
**Pull request by kicferk1**
### Context
We added a new field (`completion_time_in_minutes`) to the db. We forgot to add it to our seed files. Nothing major, but we need to do it. 

### Changes proposed in this pull request
As per title.

### Guidance to review
It is adding a field and a bunch of nils to both files. Github should be able to show you the diff if you want to read through it.

### CODE REVIEW

**Comment by amazimbe** [comment]
I can't actually view the differences as the files are just too large. All I'm able to view is the raw file.

**Comment by kicferk1** [comment]
> I can't actually view the differences as the files are just too large. All I'm able to view is the raw file.

What the hell, github shows the diff to me when I click to open it. Arghhh.

I guess you can check out the branch and compare it using a git client locally?

**Review by xswoodsx — APPROVED** [review]
I could view the differences fine, LGTM :)

**Review by seb-siem-softwire — APPROVED** [review]
👍

**Pull request merged**
